### ISSUE TITLE
1.7.10 无法加载

### ISSUE THREAD

**Issue by HowardZHY** [AmarokIce/RecipesExport#1]
从百科下载的

[14:57:04] [Client thread/DEBUG] [FML/]: Examining file RecipeExport-1.0-1.7.10.jar for potential mods
[14:57:04] [Client thread/TRACE] [FML/]: Located mcmod.info file in file RecipeExport-1.0-1.7.10.jar
[14:57:04] [Client thread/WARN] [FML/]: Zip file RecipeExport-1.0-1.7.10.jar failed to read properly, it will be ignored
java.lang.RuntimeException: Empty reference 
	at cpw.mods.fml.common.versioning.VersionParser.parseVersionReference(VersionParser.java:44) ~[VersionParser.class:?]
	at cpw.mods.fml.common.MetadataCollection$ArtifactVersionAdapter.read(MetadataCollection.java:120) ~[MetadataCollection$ArtifactVersionAdapter.class:?]
	at cpw.mods.fml.common.MetadataCollection$ArtifactVersionAdapter.read(MetadataCollection.java:108) ~[MetadataCollection$ArtifactVersionAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:841) ~[Gson.class:?]
	at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:64) ~[MetadataCollection.class:?]
	at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [JarDiscoverer.class:?]
	at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
	at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
	at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:131) [ModDiscoverer.class:?]
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]

**Comment by HowardZHY** [comment]
建议尝试修改`@Mod`注解为
`@Mod(modid = "recipe_export", version = "1.1", name = "RecipeExport", acceptedMinecraftVersions = "*", acceptableRemoteVersions = "*")`

**Comment by AmarokIce** [comment]
`@Mod`注解拥有相应的默认值，因此与`@Mod`无关，此问题是mod.info的dependencies Array中存在空字符串，Forge无法确认依赖关系
目前已经修复此情况，重新打包与上传

这个Issue将会关闭
