### ISSUE TITLE
1.7.10 当输入modid时在执行此指令时出现了未知的错误

### ISSUE THREAD

**Issue by HowardZHY** [AmarokIce/RecipesExport#2]
[21:02:00] [Client thread/INFO]: [CHAT] mcp, FML, Forge, unimixins, unimixins-mixin, unimixins-compat, mixingasm, spongemixins, mixinbooterlegacy, gasstation, gtnhmixins, mixinextras, compatlib, craftguide, eternisles, recipe_export
[21:02:01] [Client thread/INFO]: [CHAT] 在执行此指令时出现了未知的错误
[21:02:01] [Server thread/ERROR]: Couldn't process command: 'recipes_export eternisles'
java.lang.NullPointerException
	at cn.mcmod.recipe_export.RecipeExport$CommandExport.checkRecipeWithModid(RecipeExport.java:78) ~[RecipeExport$CommandExport.class:?]
	at cn.mcmod.recipe_export.RecipeExport$CommandExport.func_71515_b(RecipeExport.java:69) ~[RecipeExport$CommandExport.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21:02:04] [Client thread/INFO]: [CHAT] mcp, FML, Forge, unimixins, unimixins-mixin, unimixins-compat, mixingasm, spongemixins, mixinbooterlegacy, gasstation, gtnhmixins, mixinextras, compatlib, craftguide, eternisles, recipe_export
[21:02:08] [Server thread/ERROR]: Couldn't process command: 'recipes_export craftguide'
java.lang.NullPointerException
	at cn.mcmod.recipe_export.RecipeExport$CommandExport.checkRecipeWithModid(RecipeExport.java:78) ~[RecipeExport$CommandExport.class:?]
	at cn.mcmod.recipe_export.RecipeExport$CommandExport.func_71515_b(RecipeExport.java:69) ~[RecipeExport$CommandExport.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21:02:01] [Client thread/INFO]: [CHAT] 在执行此指令时出现了未知的错误

**Comment by AmarokIce** [comment]
这个地方能有空值... 神奇，1.2新增捕捉
